export const nations = [
  { id: 1, name: "阿富汗", englishName: "Afghanistan", code: "AF", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/af.png" },
  { id: 2, name: "阿尔巴尼亚", englishName: "Albania", code: "AL", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/al.png" },
  { id: 3, name: "阿尔及利亚", englishName: "Algeria", code: "DZ", continent: "非洲", flagUrl: "https://flagcdn.com/w160/dz.png" },
  { id: 4, name: "安道尔", englishName: "Andorra", code: "AD", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/ad.png" },
  { id: 5, name: "安哥拉", englishName: "Angola", code: "AO", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ao.png" },
  { id: 6, name: "安提瓜和巴布达", englishName: "Antigua and Barbuda", code: "AG", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/ag.png" },
  { id: 7, name: "阿根廷", englishName: "Argentina", code: "AR", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/ar.png" },
  { id: 8, name: "亚美尼亚", englishName: "Armenia", code: "AM", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/am.png" },
  { id: 9, name: "澳大利亚", englishName: "Australia", code: "AU", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/au.png" },
  { id: 10, name: "奥地利", englishName: "Austria", code: "AT", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/at.png" },
  { id: 11, name: "阿塞拜疆", englishName: "Azerbaijan", code: "AZ", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/az.png" },
  { id: 12, name: "巴哈马", englishName: "Bahamas", code: "BS", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/bs.png" },
  { id: 13, name: "巴林", englishName: "Bahrain", code: "BH", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/bh.png" },
  { id: 14, name: "孟加拉国", englishName: "Bangladesh", code: "BD", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/bd.png" },
  { id: 15, name: "巴巴多斯", englishName: "Barbados", code: "BB", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/bb.png" },
  { id: 16, name: "白俄罗斯", englishName: "Belarus", code: "BY", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/by.png" },
  { id: 17, name: "比利时", englishName: "Belgium", code: "BE", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/be.png" },
  { id: 18, name: "伯利兹", englishName: "Belize", code: "BZ", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/bz.png" },
  { id: 19, name: "贝宁", englishName: "Benin", code: "BJ", continent: "非洲", flagUrl: "https://flagcdn.com/w160/bj.png" },
  { id: 20, name: "不丹", englishName: "Bhutan", code: "BT", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/bt.png" },
  { id: 21, name: "玻利维亚", englishName: "Bolivia", code: "BO", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/bo.png" },
  { id: 22, name: "波斯尼亚和黑塞哥维那", englishName: "Bosnia and Herzegovina", code: "BA", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/ba.png" },
  { id: 23, name: "博茨瓦纳", englishName: "Botswana", code: "BW", continent: "非洲", flagUrl: "https://flagcdn.com/w160/bw.png" },
  { id: 24, name: "巴西", englishName: "Brazil", code: "BR", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/br.png" },
  { id: 25, name: "文莱", englishName: "Brunei", code: "BN", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/bn.png" },
  { id: 26, name: "保加利亚", englishName: "Bulgaria", code: "BG", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/bg.png" },
  { id: 27, name: "布基纳法索", englishName: "Burkina Faso", code: "BF", continent: "非洲", flagUrl: "https://flagcdn.com/w160/bf.png" },
  { id: 28, name: "布隆迪", englishName: "Burundi", code: "BI", continent: "非洲", flagUrl: "https://flagcdn.com/w160/bi.png" },
  { id: 29, name: "佛得角", englishName: "Cabo Verde", code: "CV", continent: "非洲", flagUrl: "https://flagcdn.com/w160/cv.png" },
  { id: 30, name: "柬埔寨", englishName: "Cambodia", code: "KH", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/kh.png" },
  { id: 31, name: "喀麦隆", englishName: "Cameroon", code: "CM", continent: "非洲", flagUrl: "https://flagcdn.com/w160/cm.png" },
  { id: 32, name: "加拿大", englishName: "Canada", code: "CA", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/ca.png" },
  { id: 33, name: "中非共和国", englishName: "Central African Republic", code: "CF", continent: "非洲", flagUrl: "https://flagcdn.com/w160/cf.png" },
  { id: 34, name: "乍得", englishName: "Chad", code: "TD", continent: "非洲", flagUrl: "https://flagcdn.com/w160/td.png" },
  { id: 35, name: "智利", englishName: "Chile", code: "CL", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/cl.png" },
  { id: 36, name: "中国", englishName: "China", code: "CN", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/cn.png" },
  { id: 37, name: "哥伦比亚", englishName: "Colombia", code: "CO", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/co.png" },
  { id: 38, name: "科摩罗", englishName: "Comoros", code: "KM", continent: "非洲", flagUrl: "https://flagcdn.com/w160/km.png" },
  { id: 39, name: "刚果共和国", englishName: "Republic of the Congo", code: "CG", continent: "非洲", flagUrl: "https://flagcdn.com/w160/cg.png" },
  { id: 40, name: "刚果民主共和国", englishName: "Democratic Republic of the Congo", code: "CD", continent: "非洲", flagUrl: "https://flagcdn.com/w160/cd.png" },
  { id: 41, name: "哥斯达黎加", englishName: "Costa Rica", code: "CR", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/cr.png" },
  { id: 42, name: "科特迪瓦", englishName: "Côte d’Ivoire", code: "CI", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ci.png" },
  { id: 43, name: "克罗地亚", englishName: "Croatia", code: "HR", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/hr.png" },
  { id: 44, name: "古巴", englishName: "Cuba", code: "CU", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/cu.png" },
  { id: 45, name: "塞浦路斯", englishName: "Cyprus", code: "CY", continent: "欧洲/亚洲", flagUrl: "https://flagcdn.com/w160/cy.png" },
  { id: 46, name: "捷克", englishName: "Czechia", code: "CZ", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/cz.png" },
  { id: 47, name: "丹麦", englishName: "Denmark", code: "DK", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/dk.png" },
  { id: 48, name: "吉布提", englishName: "Djibouti", code: "DJ", continent: "非洲", flagUrl: "https://flagcdn.com/w160/dj.png" },
  { id: 49, name: "多米尼克", englishName: "Dominica", code: "DM", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/dm.png" },
  { id: 50, name: "多米尼加共和国", englishName: "Dominican Republic", code: "DO", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/do.png" },
  { id: 51, name: "厄瓜多尔", englishName: "Ecuador", code: "EC", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/ec.png" },
  { id: 52, name: "埃及", englishName: "Egypt", code: "EG", continent: "非洲", flagUrl: "https://flagcdn.com/w160/eg.png" },
  { id: 53, name: "萨尔瓦多", englishName: "El Salvador", code: "SV", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/sv.png" },
  { id: 54, name: "赤道几内亚", englishName: "Equatorial Guinea", code: "GQ", continent: "非洲", flagUrl: "https://flagcdn.com/w160/gq.png" },
  { id: 55, name: "厄立特里亚", englishName: "Eritrea", code: "ER", continent: "非洲", flagUrl: "https://flagcdn.com/w160/er.png" },
  { id: 56, name: "爱沙尼亚", englishName: "Estonia", code: "EE", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/ee.png" },
  { id: 57, name: "斯威士兰", englishName: "Eswatini", code: "SZ", continent: "非洲", flagUrl: "https://flagcdn.com/w160/sz.png" },
  { id: 58, name: "埃塞俄比亚", englishName: "Ethiopia", code: "ET", continent: "非洲", flagUrl: "https://flagcdn.com/w160/et.png" },
  { id: 59, name: "斐济", englishName: "Fiji", code: "FJ", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/fj.png" },
  { id: 60, name: "芬兰", englishName: "Finland", code: "FI", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/fi.png" },
  { id: 61, name: "法国", englishName: "France", code: "FR", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/fr.png" },
  { id: 62, name: "加蓬", englishName: "Gabon", code: "GA", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ga.png" },
  { id: 63, name: "冈比亚", englishName: "Gambia", code: "GM", continent: "非洲", flagUrl: "https://flagcdn.com/w160/gm.png" },
  { id: 64, name: "格鲁吉亚", englishName: "Georgia", code: "GE", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/ge.png" },
  { id: 65, name: "德国", englishName: "Germany", code: "DE", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/de.png" },
  { id: 66, name: "加纳", englishName: "Ghana", code: "GH", continent: "非洲", flagUrl: "https://flagcdn.com/w160/gh.png" },
  { id: 67, name: "希腊", englishName: "Greece", code: "GR", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/gr.png" },
  { id: 68, name: "格林纳达", englishName: "Grenada", code: "GD", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/gd.png" },
  { id: 69, name: "危地马拉", englishName: "Guatemala", code: "GT", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/gt.png" },
  { id: 70, name: "几内亚", englishName: "Guinea", code: "GN", continent: "非洲", flagUrl: "https://flagcdn.com/w160/gn.png" },
  { id: 71, name: "几内亚比绍", englishName: "Guinea-Bissau", code: "GW", continent: "非洲", flagUrl: "https://flagcdn.com/w160/gw.png" },
  { id: 72, name: "圭亚那", englishName: "Guyana", code: "GY", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/gy.png" },
  { id: 73, name: "海地", englishName: "Haiti", code: "HT", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/ht.png" },
  { id: 74, name: "洪都拉斯", englishName: "Honduras", code: "HN", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/hn.png" },
  { id: 75, name: "匈牙利", englishName: "Hungary", code: "HU", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/hu.png" },
  { id: 76, name: "冰岛", englishName: "Iceland", code: "IS", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/is.png" },
  { id: 77, name: "印度", englishName: "India", code: "IN", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/in.png" },
  { id: 78, name: "印度尼西亚", englishName: "Indonesia", code: "ID", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/id.png" },
  { id: 79, name: "伊朗", englishName: "Iran", code: "IR", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/ir.png" },
  { id: 80, name: "伊拉克", englishName: "Iraq", code: "IQ", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/iq.png" },
  { id: 81, name: "爱尔兰", englishName: "Ireland", code: "IE", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/ie.png" },
  { id: 82, name: "以色列", englishName: "Israel", code: "IL", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/il.png" },
  { id: 83, name: "意大利", englishName: "Italy", code: "IT", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/it.png" },
  { id: 84, name: "牙买加", englishName: "Jamaica", code: "JM", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/jm.png" },
  { id: 85, name: "日本", englishName: "Japan", code: "JP", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/jp.png" },
  { id: 86, name: "约旦", englishName: "Jordan", code: "JO", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/jo.png" },
  { id: 87, name: "哈萨克斯坦", englishName: "Kazakhstan", code: "KZ", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/kz.png" },
  { id: 88, name: "肯尼亚", englishName: "Kenya", code: "KE", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ke.png" },
  { id: 89, name: "基里巴斯", englishName: "Kiribati", code: "KI", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/ki.png" },
  { id: 90, name: "朝鲜", englishName: "North Korea", code: "KP", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/kp.png" },
  { id: 91, name: "韩国", englishName: "South Korea", code: "KR", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/kr.png" },
  { id: 92, name: "科威特", englishName: "Kuwait", code: "KW", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/kw.png" },
  { id: 93, name: "吉尔吉斯斯坦", englishName: "Kyrgyzstan", code: "KG", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/kg.png" },
  { id: 94, name: "老挝", englishName: "Laos", code: "LA", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/la.png" },
  { id: 95, name: "拉脱维亚", englishName: "Latvia", code: "LV", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/lv.png" },
  { id: 96, name: "黎巴嫩", englishName: "Lebanon", code: "LB", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/lb.png" },
  { id: 97, name: "莱索托", englishName: "Lesotho", code: "LS", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ls.png" },
  { id: 98, name: "利比里亚", englishName: "Liberia", code: "LR", continent: "非洲", flagUrl: "https://flagcdn.com/w160/lr.png" },
  { id: 99, name: "利比亚", englishName: "Libya", code: "LY", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ly.png" },
  { id: 100, name: "列支敦士登", englishName: "Liechtenstein", code: "LI", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/li.png" },
  { id: 101, name: "立陶宛", englishName: "Lithuania", code: "LT", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/lt.png" },
  { id: 102, name: "卢森堡", englishName: "Luxembourg", code: "LU", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/lu.png" },
  { id: 103, name: "马达加斯加", englishName: "Madagascar", code: "MG", continent: "非洲", flagUrl: "https://flagcdn.com/w160/mg.png" },
  { id: 104, name: "马拉维", englishName: "Malawi", code: "MW", continent: "非洲", flagUrl: "https://flagcdn.com/w160/mw.png" },
  { id: 105, name: "马来西亚", englishName: "Malaysia", code: "MY", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/my.png" },
  { id: 106, name: "马尔代夫", englishName: "Maldives", code: "MV", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/mv.png" },
  { id: 107, name: "马里", englishName: "Mali", code: "ML", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ml.png" },
  { id: 108, name: "马耳他", englishName: "Malta", code: "MT", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/mt.png" },
  { id: 109, name: "马绍尔群岛", englishName: "Marshall Islands", code: "MH", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/mh.png" },
  { id: 110, name: "毛里塔尼亚", englishName: "Mauritania", code: "MR", continent: "非洲", flagUrl: "https://flagcdn.com/w160/mr.png" },
  { id: 111, name: "毛里求斯", englishName: "Mauritius", code: "MU", continent: "非洲", flagUrl: "https://flagcdn.com/w160/mu.png" },
  { id: 112, name: "墨西哥", englishName: "Mexico", code: "MX", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/mx.png" },
  { id: 113, name: "密克罗尼西亚", englishName: "Micronesia", code: "FM", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/fm.png" },
  { id: 114, name: "摩尔多瓦", englishName: "Moldova", code: "MD", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/md.png" },
  { id: 115, name: "摩纳哥", englishName: "Monaco", code: "MC", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/mc.png" },
  { id: 116, name: "蒙古", englishName: "Mongolia", code: "MN", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/mn.png" },
  { id: 117, name: "黑山", englishName: "Montenegro", code: "ME", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/me.png" },
  { id: 118, name: "摩洛哥", englishName: "Morocco", code: "MA", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ma.png" },
  { id: 119, name: "莫桑比克", englishName: "Mozambique", code: "MZ", continent: "非洲", flagUrl: "https://flagcdn.com/w160/mz.png" },
  { id: 120, name: "缅甸", englishName: "Myanmar", code: "MM", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/mm.png" },
  { id: 121, name: "纳米比亚", englishName: "Namibia", code: "NA", continent: "非洲", flagUrl: "https://flagcdn.com/w160/na.png" },
  { id: 122, name: "瑙鲁", englishName: "Nauru", code: "NR", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/nr.png" },
  { id: 123, name: "尼泊尔", englishName: "Nepal", code: "NP", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/np.png" },
  { id: 124, name: "荷兰", englishName: "Netherlands", code: "NL", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/nl.png" },
  { id: 125, name: "新西兰", englishName: "New Zealand", code: "NZ", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/nz.png" },
  { id: 126, name: "尼加拉瓜", englishName: "Nicaragua", code: "NI", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/ni.png" },
  { id: 127, name: "尼日尔", englishName: "Niger", code: "NE", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ne.png" },
  { id: 128, name: "尼日利亚", englishName: "Nigeria", code: "NG", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ng.png" },
  { id: 129, name: "北马其顿", englishName: "North Macedonia", code: "MK", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/mk.png" },
  { id: 130, name: "挪威", englishName: "Norway", code: "NO", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/no.png" },
  { id: 131, name: "阿曼", englishName: "Oman", code: "OM", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/om.png" },
  { id: 132, name: "巴基斯坦", englishName: "Pakistan", code: "PK", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/pk.png" },
  { id: 133, name: "帕劳", englishName: "Palau", code: "PW", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/pw.png" },
  { id: 134, name: "巴勒斯坦", englishName: "Palestine", code: "PS", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/ps.png" },
  { id: 135, name: "巴拿马", englishName: "Panama", code: "PA", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/pa.png" },
  { id: 136, name: "巴布亚新几内亚", englishName: "Papua New Guinea", code: "PG", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/pg.png" },
  { id: 137, name: "巴拉圭", englishName: "Paraguay", code: "PY", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/py.png" },
  { id: 138, name: "秘鲁", englishName: "Peru", code: "PE", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/pe.png" },
  { id: 139, name: "菲律宾", englishName: "Philippines", code: "PH", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/ph.png" },
  { id: 140, name: "波兰", englishName: "Poland", code: "PL", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/pl.png" },
  { id: 141, name: "葡萄牙", englishName: "Portugal", code: "PT", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/pt.png" },
  { id: 142, name: "卡塔尔", englishName: "Qatar", code: "QA", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/qa.png" },
  { id: 143, name: "罗马尼亚", englishName: "Romania", code: "RO", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/ro.png" },
  { id: 144, name: "俄罗斯", englishName: "Russia", code: "RU", continent: "欧洲/亚洲", flagUrl: "https://flagcdn.com/w160/ru.png" },
  { id: 145, name: "卢旺达", englishName: "Rwanda", code: "RW", continent: "非洲", flagUrl: "https://flagcdn.com/w160/rw.png" },
  { id: 146, name: "圣基茨和尼维斯", englishName: "Saint Kitts and Nevis", code: "KN", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/kn.png" },
  { id: 147, name: "圣卢西亚", englishName: "Saint Lucia", code: "LC", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/lc.png" },
  { id: 148, name: "圣文森特和格林纳丁斯", englishName: "Saint Vincent and the Grenadines", code: "VC", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/vc.png" },
  { id: 149, name: "萨摩亚", englishName: "Samoa", code: "WS", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/ws.png" },
  { id: 150, name: "圣马力诺", englishName: "San Marino", code: "SM", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/sm.png" },
  { id: 151, name: "圣多美和普林西比", englishName: "São Tomé and Príncipe", code: "ST", continent: "非洲", flagUrl: "https://flagcdn.com/w160/st.png" },
  { id: 152, name: "沙特阿拉伯", englishName: "Saudi Arabia", code: "SA", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/sa.png" },
  { id: 153, name: "塞内加尔", englishName: "Senegal", code: "SN", continent: "非洲", flagUrl: "https://flagcdn.com/w160/sn.png" },
  { id: 154, name: "塞尔维亚", englishName: "Serbia", code: "RS", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/rs.png" },
  { id: 155, name: "塞舌尔", englishName: "Seychelles", code: "SC", continent: "非洲", flagUrl: "https://flagcdn.com/w160/sc.png" },
  { id: 156, name: "塞拉利昂", englishName: "Sierra Leone", code: "SL", continent: "非洲", flagUrl: "https://flagcdn.com/w160/sl.png" },
  { id: 157, name: "新加坡", englishName: "Singapore", code: "SG", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/sg.png" },
  { id: 158, name: "斯洛伐克", englishName: "Slovakia", code: "SK", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/sk.png" },
  { id: 159, name: "斯洛文尼亚", englishName: "Slovenia", code: "SI", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/si.png" },
  { id: 160, name: "所罗门群岛", englishName: "Solomon Islands", code: "SB", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/sb.png" },
  { id: 161, name: "索马里", englishName: "Somalia", code: "SO", continent: "非洲", flagUrl: "https://flagcdn.com/w160/so.png" },
  { id: 162, name: "南非", englishName: "South Africa", code: "ZA", continent: "非洲", flagUrl: "https://flagcdn.com/w160/za.png" },
  { id: 163, name: "南苏丹", englishName: "South Sudan", code: "SS", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ss.png" },
  { id: 164, name: "西班牙", englishName: "Spain", code: "ES", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/es.png" },
  { id: 165, name: "斯里兰卡", englishName: "Sri Lanka", code: "LK", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/lk.png" },
  { id: 166, name: "苏丹", englishName: "Sudan", code: "SD", continent: "非洲", flagUrl: "https://flagcdn.com/w160/sd.png" },
  { id: 167, name: "苏里南", englishName: "Suriname", code: "SR", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/sr.png" },
  { id: 168, name: "瑞典", englishName: "Sweden", code: "SE", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/se.png" },
  { id: 169, name: "瑞士", englishName: "Switzerland", code: "CH", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/ch.png" },
  { id: 170, name: "叙利亚", englishName: "Syria", code: "SY", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/sy.png" },
  { id: 171, name: "台湾", englishName: "Taiwan", code: "TW", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/tw.png" },
  { id: 172, name: "塔吉克斯坦", englishName: "Tajikistan", code: "TJ", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/tj.png" },
  { id: 173, name: "坦桑尼亚", englishName: "Tanzania", code: "TZ", continent: "非洲", flagUrl: "https://flagcdn.com/w160/tz.png" },
  { id: 174, name: "泰国", englishName: "Thailand", code: "TH", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/th.png" },
  { id: 175, name: "东帝汶", englishName: "Timor-Leste", code: "TL", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/tl.png" },
  { id: 176, name: "多哥", englishName: "Togo", code: "TG", continent: "非洲", flagUrl: "https://flagcdn.com/w160/tg.png" },
  { id: 177, name: "汤加", englishName: "Tonga", code: "TO", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/to.png" },
  { id: 178, name: "特立尼达和多巴哥", englishName: "Trinidad and Tobago", code: "TT", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/tt.png" },
  { id: 179, name: "突尼斯", englishName: "Tunisia", code: "TN", continent: "非洲", flagUrl: "https://flagcdn.com/w160/tn.png" },
  { id: 180, name: "土耳其", englishName: "Türkiye", code: "TR", continent: "欧洲/亚洲", flagUrl: "https://flagcdn.com/w160/tr.png" },
  { id: 181, name: "土库曼斯坦", englishName: "Turkmenistan", code: "TM", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/tm.png" },
  { id: 182, name: "图瓦卢", englishName: "Tuvalu", code: "TV", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/tv.png" },
  { id: 183, name: "乌干达", englishName: "Uganda", code: "UG", continent: "非洲", flagUrl: "https://flagcdn.com/w160/ug.png" },
  { id: 184, name: "乌克兰", englishName: "Ukraine", code: "UA", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/ua.png" },
  { id: 185, name: "阿拉伯联合酋长国", englishName: "United Arab Emirates", code: "AE", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/ae.png" },
  { id: 186, name: "英国", englishName: "United Kingdom", code: "GB", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/gb.png" },
  { id: 187, name: "美国", englishName: "United States", code: "US", continent: "北美洲", flagUrl: "https://flagcdn.com/w160/us.png" },
  { id: 188, name: "乌拉圭", englishName: "Uruguay", code: "UY", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/uy.png" },
  { id: 189, name: "乌兹别克斯坦", englishName: "Uzbekistan", code: "UZ", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/uz.png" },
  { id: 190, name: "瓦努阿图", englishName: "Vanuatu", code: "VU", continent: "大洋洲", flagUrl: "https://flagcdn.com/w160/vu.png" },
  { id: 191, name: "梵蒂冈", englishName: "Vatican City", code: "VA", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/va.png" },
  { id: 192, name: "委内瑞拉", englishName: "Venezuela", code: "VE", continent: "南美洲", flagUrl: "https://flagcdn.com/w160/ve.png" },
  { id: 193, name: "越南", englishName: "Vietnam", code: "VN", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/vn.png" },
  { id: 194, name: "也门", englishName: "Yemen", code: "YE", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/ye.png" },
  { id: 195, name: "赞比亚", englishName: "Zambia", code: "ZM", continent: "非洲", flagUrl: "https://flagcdn.com/w160/zm.png" },
  { id: 196, name: "津巴布韦", englishName: "Zimbabwe", code: "ZW", continent: "非洲", flagUrl: "https://flagcdn.com/w160/zw.png" },
  { id: 197, name: "香港", englishName: "Hong Kong", code: "HK", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/hk.png" },
  { id: 198, name: "澳门", englishName: "Macau", code: "MO", continent: "亚洲", flagUrl: "https://flagcdn.com/w160/mo.png" },
  { id: 199, name: "科索沃", englishName: "Kosovo", code: "XK", continent: "欧洲", flagUrl: "https://flagcdn.com/w160/xk.png" },
];
