export const gameStories = [
  {
    id: `switch-story`,
    title: `Nintendo Switch 的故事`,
    type: `主机故事`,
    brand: `任天堂`,
    period: `2017年至今`,
    icon: `🎮`,
    summary: `Switch 把家用主机和掌机结合在一起，让玩家可以在电视、桌面和手持模式之间自由切换。`,
    timeline: [
      { year: `2015年`, event: `任天堂在 Wii U 表现不佳后，开始准备代号 NX 的新主机。` },
      { year: `2016年`, event: `任天堂正式公开 Nintendo Switch 的概念：一台可以带出门的家用主机。` },
      { year: `2017年`, event: `Nintendo Switch 发售，《塞尔达传说：旷野之息》成为首发代表作。` },
      { year: `2018年`, event: `《任天堂明星大乱斗 特别版》推出，强化多人派对与竞技玩法。` },
      { year: `2019年`, event: `Switch Lite 推出，主打更轻便的纯掌机体验。` },
      { year: `2020年`, event: `《集合啦！动物森友会》爆红，Switch 在全球家庭中快速普及。` },
      { year: `2021年`, event: `Switch OLED 款推出，改善屏幕、支架与音效体验。` },
      { year: `2023年`, event: `《塞尔达传说：王国之泪》再次证明 Switch 的游戏生命力。` },
    ],
    story: `Nintendo Switch 的成功来自一个很简单但很强的想法：玩家不应该被固定在电视前面。Wii U 时代，任天堂曾尝试用手柄屏幕带来双屏玩法，但市场反应不理想。Switch 改变方向，把主机本体做成可以随身携带的平板，再通过底座连接电视。这样一来，玩家可以在客厅玩，也可以带去学校、旅行或朋友家。Joy-Con 手柄可以拆下来变成两只小手柄，方便多人同乐。Switch 的游戏策略也很清楚：用《塞尔达传说》《马里奥》《宝可梦》《动物森友会》《大乱斗》等强大第一方游戏吸引玩家。它不是单纯追求最高画质，而是强调玩法、方便、家庭娱乐和独特体验。Switch 证明，一台主机只要概念清楚、游戏阵容强，就能在竞争激烈的市场中成功。`,
    impact: `Switch 重新定义了掌机与家用主机的边界，也让任天堂重新回到游戏主机市场的核心位置。`,
    keyGames: [
      `塞尔达传说：旷野之息`,
      `超级马里奥 奥德赛`,
      `马力欧卡丁车8 豪华版`,
      `任天堂明星大乱斗 特别版`,
      `集合啦！动物森友会`,
      `塞尔达传说：王国之泪`,
    ],
  },
  {
    id: `playstation-story`,
    title: `PlayStation 的故事`,
    type: `主机故事`,
    brand: `索尼`,
    period: `1994年至今`,
    icon: `🕹️`,
    summary: `PlayStation 从一次合作破裂中诞生，后来成为世界最重要的游戏主机品牌之一。`,
    timeline: [
      { year: `1980年代末`, event: `索尼原本与任天堂合作开发光盘主机配件。` },
      { year: `1991年`, event: `合作关系破裂后，索尼决定自己进入游戏主机市场。` },
      { year: `1994年`, event: `第一代 PlayStation 在日本发售，以 CD 光盘和 3D 游戏打开市场。` },
      { year: `2000年`, event: `PlayStation 2 发售，凭借 DVD 播放、强大游戏阵容和向下兼容大获成功。` },
      { year: `2006年`, event: `PlayStation 3 发售，主打蓝光、高清画面和网络服务。` },
      { year: `2013年`, event: `PlayStation 4 发售，凭借清晰定位和大量优秀游戏取得成功。` },
      { year: `2020年`, event: `PlayStation 5 发售，带来高速 SSD、DualSense 触觉反馈和新世代画面。` },
    ],
    story: `PlayStation 的起点很戏剧化。索尼最初并不是传统游戏主机公司，而是电子和影音科技巨头。它原本计划与任天堂合作开发光盘系统，但合作破裂后，索尼决定自己推出主机。第一代 PlayStation 使用 CD 光盘，容量比卡带更大，适合制作过场动画、音乐和大型 3D 游戏。到了 PlayStation 2，索尼抓住 DVD 普及浪潮，让 PS2 不只是游戏机，也成为许多家庭的 DVD 播放器。加上《侠盗猎车手》《最终幻想》《合金装备》《鬼泣》等游戏，PS2 成为历史上最成功的主机之一。PS3 初期因价格和开发难度遇到挑战，但后期靠独占游戏和蓝光优势追回口碑。PS4 时代，索尼强调玩家、游戏与开发者友好策略，重新扩大优势。PS5 则进入高速读取和沉浸式控制体验的新阶段。PlayStation 的故事说明，主机成功不只是硬件强，也要有游戏阵容、价格、开发环境和品牌信任。`,
    impact: `PlayStation 推动 3D 游戏、光盘游戏、电影化叙事和家用主机大众化，深刻影响现代游戏产业。`,
    keyGames: [
      `Gran Turismo`,
      `Final Fantasy VII`,
      `Metal Gear Solid`,
      `Grand Theft Auto: San Andreas`,
      `The Last of Us`,
      `God of War`,
      `Marvel's Spider-Man`,
    ],
  },
  {
    id: `best-selling-games-story`,
    title: `年度畅销游戏的故事`,
    type: `销量故事`,
    brand: `全球游戏产业`,
    period: `1998年－2024年`,
    icon: `🏆`,
    summary: `年度畅销游戏反映了不同时代玩家的兴趣：任天堂、体育游戏、摇滚音乐游戏、GTA、使命召唤都曾统治市场。`,
    timeline: [
      { year: `1998年－2000年`, event: `任天堂与宝可梦在美国年度销量榜非常强势。` },
      { year: `2001年－2006年`, event: `Madden NFL、GTA、Need for Speed 等作品长期占据主流市场。` },
      { year: `2007年－2008年`, event: `音乐游戏热潮出现，《Guitar Hero》和《Rock Band》成为现象级产品。` },
      { year: `2009年－2017年`, event: `《Call of Duty》系列进入黄金时代，多年成为年度销量冠军。` },
      { year: `2018年－2024年`, event: `《Red Dead Redemption 2》《Hogwarts Legacy》和《Call of Duty》继续展现大型品牌影响力。` },
    ],
    story: `每一年的畅销游戏都像一张游戏产业成绩单。1990年代末，任天堂凭借《塞尔达传说》《宝可梦》《大金刚》等作品统治美国市场，说明家庭娱乐和角色品牌非常强大。进入 2000年代，玩家口味开始扩大，体育游戏、开放世界游戏和动作冒险游戏成为主流。《Madden NFL》代表美国体育文化，《Grand Theft Auto》代表开放世界自由度，《Need for Speed》代表街头赛车潮流。2007年前后，音乐游戏突然爆红，玩家用塑料吉他和鼓组在客厅中体验舞台表演。随后，《Call of Duty》把电影化战争、多人联机和年度化发行结合起来，成为长期销量霸主。到了近年，虽然市场出现更多独立游戏和免费游戏，但年度销量冠军仍常由大型品牌、强宣传和跨平台发行的作品拿下。`,
    impact: `年度畅销榜让人看见游戏产业从单机卡带、3D主机、体育游戏、开放世界，到线上多人与大型IP时代的变化。`,
    keyGames: [
      `The Legend of Zelda: Ocarina of Time`,
      `Grand Theft Auto: Vice City`,
      `Guitar Hero III: Legends of Rock`,
      `Call of Duty: Modern Warfare 2`,
      `Grand Theft Auto V`,
      `Hogwarts Legacy`,
    ],
  },
];

export const annualBestSellingGames = [
  {
    id: 1,
    year: 1998,
    title: `The Legend of Zelda: Ocarina of Time`,
    chineseTitle: `塞尔达传说：时之笛`,
    publisher: `任天堂`,
    genre: `动作冒险`,
    platform: `N64`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 2,
    year: 1999,
    title: `Donkey Kong 64`,
    chineseTitle: `大金刚64`,
    publisher: `任天堂`,
    genre: `平台动作`,
    platform: `N64`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 3,
    year: 2000,
    title: `Pokemon Gold/Silver`,
    chineseTitle: `宝可梦 金／银`,
    publisher: `任天堂`,
    genre: `角色扮演`,
    platform: `Game Boy Color`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 4,
    year: 2001,
    title: `Madden NFL 2002`,
    chineseTitle: `麦登橄榄球2002`,
    publisher: `EA Sports`,
    genre: `体育`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 5,
    year: 2002,
    title: `Grand Theft Auto: Vice City`,
    chineseTitle: `侠盗猎车手：罪恶都市`,
    publisher: `Rockstar Games`,
    genre: `开放世界`,
    platform: `PS2`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 6,
    year: 2003,
    title: `Madden NFL 2004`,
    chineseTitle: `麦登橄榄球2004`,
    publisher: `EA Sports`,
    genre: `体育`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 7,
    year: 2004,
    title: `Grand Theft Auto: San Andreas`,
    chineseTitle: `侠盗猎车手：圣安地列斯`,
    publisher: `Rockstar Games`,
    genre: `开放世界`,
    platform: `PS2`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 8,
    year: 2005,
    title: `Madden NFL 06`,
    chineseTitle: `麦登橄榄球06`,
    publisher: `EA Sports`,
    genre: `体育`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 9,
    year: 2006,
    title: `Madden NFL 07`,
    chineseTitle: `麦登橄榄球07`,
    publisher: `EA Sports`,
    genre: `体育`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 10,
    year: 2007,
    title: `Guitar Hero III: Legends of Rock`,
    chineseTitle: `吉他英雄III：摇滚传奇`,
    publisher: `Activision`,
    genre: `音乐节奏`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 11,
    year: 2008,
    title: `Rock Band`,
    chineseTitle: `摇滚乐队`,
    publisher: `MTV Games`,
    genre: `音乐节奏`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 12,
    year: 2009,
    title: `Call of Duty: Modern Warfare 2`,
    chineseTitle: `使命召唤：现代战争2`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 13,
    year: 2010,
    title: `Call of Duty: Black Ops`,
    chineseTitle: `使命召唤：黑色行动`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 14,
    year: 2011,
    title: `Call of Duty: Modern Warfare 3`,
    chineseTitle: `使命召唤：现代战争3`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 15,
    year: 2012,
    title: `Call of Duty: Black Ops II`,
    chineseTitle: `使命召唤：黑色行动II`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 16,
    year: 2013,
    title: `Grand Theft Auto V`,
    chineseTitle: `侠盗猎车手V`,
    publisher: `Rockstar Games`,
    genre: `开放世界`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 17,
    year: 2014,
    title: `Call of Duty: Advanced Warfare`,
    chineseTitle: `使命召唤：高级战争`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 18,
    year: 2015,
    title: `Call of Duty: Black Ops III`,
    chineseTitle: `使命召唤：黑色行动III`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 19,
    year: 2016,
    title: `Call of Duty: Infinite Warfare`,
    chineseTitle: `使命召唤：无限战争`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 20,
    year: 2017,
    title: `Call of Duty: WWII`,
    chineseTitle: `使命召唤：二战`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 21,
    year: 2018,
    title: `Red Dead Redemption 2`,
    chineseTitle: `荒野大镖客：救赎2`,
    publisher: `Rockstar Games`,
    genre: `开放世界`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 22,
    year: 2019,
    title: `Call of Duty: Modern Warfare`,
    chineseTitle: `使命召唤：现代战争`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 23,
    year: 2020,
    title: `Call of Duty: Black Ops Cold War`,
    chineseTitle: `使命召唤：黑色行动 冷战`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 24,
    year: 2021,
    title: `Call of Duty: Vanguard`,
    chineseTitle: `使命召唤：先锋`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 25,
    year: 2022,
    title: `Call of Duty: Modern Warfare II`,
    chineseTitle: `使命召唤：现代战争II`,
    publisher: `Activision`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 26,
    year: 2023,
    title: `Hogwarts Legacy`,
    chineseTitle: `霍格沃茨之遗`,
    publisher: `Warner Bros. Games`,
    genre: `动作角色扮演`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
  {
    id: 27,
    year: 2024,
    title: `Call of Duty: Black Ops 6`,
    chineseTitle: `使命召唤：黑色行动6`,
    publisher: `Microsoft Gaming`,
    genre: `第一人称射击`,
    platform: `多平台`,
    market: `美国年度销量榜`,
    note: `此列表采用美国年度销售榜作为参考；不同地区、统计机构、实体与数字版收录方式不同，全球榜可能不同。`,
  },
];

export const gameTimeline = [
  { id: 1, year: `1972年`, event: `《Pong》让电子游戏进入大众视野。` },
  { id: 2, year: `1983年`, event: `北美游戏市场崩溃，行业经历严重信任危机。` },
  { id: 3, year: `1985年`, event: `任天堂 NES 与《超级马里奥兄弟》帮助家用主机市场复兴。` },
  { id: 4, year: `1994年`, event: `第一代 PlayStation 在日本发售，光盘游戏时代快速扩大。` },
  { id: 5, year: `2000年`, event: `PlayStation 2 发售，成为最具代表性的家用主机之一。` },
  { id: 6, year: `2006年`, event: `Wii、PS3、Xbox 360 推动体感、高清与网络服务竞争。` },
  { id: 7, year: `2013年`, event: `PS4 与 Xbox One 开启第八世代主机竞争。` },
  { id: 8, year: `2017年`, event: `Nintendo Switch 发售，混合式主机概念成功。` },
  { id: 9, year: `2020年`, event: `PS5 与 Xbox Series X/S 推出，高速SSD和新世代画面成为重点。` },
];

export const gameCategories = [`主机故事`, `销量故事`, `游戏时间线`];
